export const drugs = [
  'Abacavir Sulfate',
  'Abarelix',
  'Abatacept',
  'Abciximab',
  'Abelcet',
  'Abilify',
  'Abraxane',
  'Acamprosate Calcium',
  'Acarbose',
  'Accolate',
  'Accretropin',
  'AccuNeb',
  'Accupril',
  'Accutane',
  'Acebutolol',
  'Aceon',
  'Acetadote',
  'Acetaminophen',
  'Acetic Acid',
  'Aci-Jel',
  'Aciphex',
  'Acitretin',
  'Aclovate',
  'Acrivastine and Pseudoephedrine',
  'Actemra',
  'Acthrel',
  'Acticin',
  'Actimmune',
  'Actiq',
  'Actisite',
  'Activase',
  'Activella',
  'Actonel',
  'Actos',
  'Acular',
  'Acular LS',
  'Acuvail',
  'Acyclovir',
  'Adacel',
  'Adagen',
  'Adalat CC',
  'Adalimumab',
  'Adapalene',
  'Adcirca',
  'Adderall',
  'Adderall XR',
  'Adefovir Dipivoxil',
  'Adenoscan',
  'Adenosine',
  'Adipex-P',
  'Adoxa',
  'Adrenalin',
  'AdreView',
  'Adriamycin PFS',
  'Advair Diskus',
  'Advair HFA',
  'Advicor',
  'Aerospan HFA',
  'Afinitor',
  'Afluria',
  'Agalsidase Beta',
  'Aggrastat',
  'Aggrenox',
  'Agrylin',
  'Ak-Fluor',
  'Akineton',
  'Alamast',
  'Albendazole',
  'Albenza',
  'Albumin, Human',
  'Albuminar',
  'Albuterol Sulfate',
  'Albuterol Sulfate Inhalation Aerosol',
  'Alcaine',
  'Alclometasone Dipropionate',
  'Aldactazide',
  'Aldactone',
  'Aldara',
  'Aldesleukin',
  'Aldomet',
  'Aldoril',
  'Aldurazyme',
  'Alefacept',
  'Alemtuzumab',
  'Alendronate Sodium',
  'Alesse',
  'Alfenta',
  'Alfentanil',
  'Alfuzosin HCl',
  'Alglucosidase Alfa',
  'Alimta',
  'Alinia',
  'Alitretinoin',
  'Alkeran',
  'Allegra',
  'Allegra-D',
  'Allegra D 24 Hour',
  'Allernaze',
  'Alli',
  'Allopurinol',
  'Almotriptan Malate',
  'Alocril',
  'Alomide',
  'Aloprim',
  'Alora',
  'Alosetron Hydrochloride',
  'Aloxi',
  'Alphanate',
  'Alprazolam',
  'Alprostadil',
  'Alrex',
  'Alsuma',
  'Altabax',
  'Altace',
  'Alteplase',
  'Altocor',
  'Altoprev',
  'Altretamine',
  'Alupent',
  'Alvesco',
  'Amantadine Hydrochloride',
  'Amaryl',
  'Ambien',
  'Ambien CR',
  'Ambisome',
  'Amerge',
  'Americaine',
  'Amevive',
  'Amicar',
  'Amifostine',
  'Amikacin',
  'Benadryl',
  'Benazepril',
  'Benefix',
  'Benicar',
  'Benicar HCT',
  'Bentyl',
  'BenzaClin',
  'Benzagel',
  'Benzamycin',
  'Benzocaine',
  'Benzonatate',
  'Benzoyl Peroxide Gel',
  'Benzphetamine',
  'Benztropine Mesylate',
  'Bepreve',
  'Bepridil',
  'Beractant',
  'Besivance',
  'Betagan',
  'Betamethasone',
  'Betamethasone Dipropionate',
  'Betapace',
  'Betapace AF',
  'Exjade',
  'Extavia',
  'Extended Phenytoin Sodium',
  'Extina',
  'Extraneal',
  'Exubera',
  'Ezetimibe',
  'Ezetimibe and Simvastatin',
  'Fabrazyme',
  'Factive',
  'Factor IX Complex',
  'Factrel',
  'Famciclovir',
  'Famotidine',
  'Famotidine Injection',
  'Famvir',
  'Fanapt',
  'Fansidar',
  'Fareston',
  'Faslodex',
  'Polysulfate Sodium',
  'Pentothal',
  'Pentoxifylline',
  'Pepcid',
  'Percocet',
  'Percodan',
  'Perflutren',
  'Perforomist',
  'Pergolide Mesylate',
  'Perindopril Erbumine',
  'Periochip',
  'Periostat',
  'Permax',
  'Permethrin',
  'Perphenazine',
  'Persantine',
  'Persantine IV',
  'Pexeva',
  'Pfizerpen',
  'Phenazopyridine',
  'Phendimetrazine Tartrate',
  'Phenelzine',
  'Phenergan',
  'Phenobarbital',
  'Phenoxybenzamine',
  'Phentermine',
  'Phentermine Hydrochloride',
  'Phentolamine Mesylate',
  'Phenylephrine HCl',
  'Phenylephrine Hydrochloride',
  'Phenytoin',
  'Phisohex',
  'Phoslo',
  'Phosphate',
  'Phosphocol',
  'Phospholine Iodide',
  'Photofrin',
  'Physostigmine Salicylate',
  'Phytonadione',
  'Pilocarpine',
  'Pilocarpine Hydrochloride',
  'Pilopine HS',
  'Pimecrolimus',
  'Pimozide',
  'Pindolol',
  'Pioglitazone Hcl',
  'Piperacillin / Tazobactam',
  'Pipracil',
  'Pirbuterol',
  'Piroxicam',
  'Pitavastatin',
  'Pitocin',
  'Pitressin',
  'Plan B',
  'Plaquenil',
  'PlasmaLyte A',
  'Plavix',
  'Plenaxis',
  'Plendil',
  'Plerixafor',
  'Pletal',
  'Pliaglis',
  'Plicamycin',
  'Pneumococcal 7-valent vaccine',
  'Pneumococcal Vaccine Polyvalent',
  'Pneumovax',
  'Podocon-25',
  'Podofilox',
  'Podophyllin',
  'Polidocanol',
  'Polifeprosan 20',
  'Poliovirus Vaccine',
  'Polyethylene Glycol 3350',
  'Polymyxin B',
  'Polymyxin B Sulfate',
  'Polysaccharides',
  'Polythiazide',
  'Pondimin',
  'Ponstel',
  'Poractant Alfa',
  'Porfimer Sodium',
  'Posaconazole',
  'Potassium Acetate',
  'Potassium Chloride',
  'Potassium Citrate',
  'Pralatrexate',
  'Pralidoxime Chloride',
  'Pramipexole',
  'Pramlintide Acetate',
  'Prandimet',
  'Prandin',
  'Prasugrel',
  'Pravachol',
  'Pravastatin Sodium',
  'Praziquantel',
  'Prazosin HCl',
  'Precedex',
  'Precose',
  'Pred Forte',
  'Pred-G',
  'Prednicarbate',
  'Prednisolone',
  'Prednisolone Acetate',
  'Prednisolone Sodium Phosphate',
  'Prednisone',
  'Prefest',
  'Pregabalin',
  'Pregnyl',
  'Prelone',
  'Premarin',
  'Prempro, Premphase',
  'Prepidil',
  'Prevacid',
  'Prevnar',
  'Prevpac',
  'Prezista',
  'Prialt',
  'Priftin',
  'Prilosec',
  'Primacor',
  'Primaquine',
  'Primatene Mist',
  'Primaxin I.V.',
  'Primidone',
  'Principen',
  'Prinivil',
  'Prinzide',
  'Pristiq',
  'Privigen',
  'Proair HFA',
  'Proamatine',
  'Probenecid and Colchicine',
  'Procainamide',
  'Procalamine',
  'Procan Sr',
  'Procarbazine',
  'Procardia',
  'Prochlorperazine',
  'Prochlorperazine Maleate',
  'Procrit',
  'Proctofoam HC',
  'Progesterone',
  'Proglycem',
  'Prograf',
  'ProHance',
  'Prolastin',
  'Proleukin',
  'Prolia',
  'Prolixin',
  'Promacta',
  'Promethazine',
  'Promethazine HCl',
  'Promethazine Hydrochloride',
  'Prometrium',
  'Pronestyl',
  'Propafenone',
  'Proparacaine Hydrochloride',
  'Propecia',
  'Propine',
  'Propofol',
  'Propoxyphene',
  'Propoxyphene Napsylate',
  'Propranolol',
  'Propranolol Hydrochloride',
  'Propulsid',
  'Propylthiouracil',
  'Proquin XR',
  'Proscar',
  'Prosom',
  'Prostigmin',
  'Prostin E2',
  'Prostin VR Pediatric',
  'Protamine',
  'Protamines',
  'Protein C Concentrate',
  'Protirelin',
  'Protonix',
  'Protonix I.V.',
  'Protopic',
  'Protriptyline Hydrochloride',
  'Protropin',
  'Proventil HFA',
  'Provera',
  'Provigil',
  'Provisc',
  'Provocholine',
  'Prozac',
  'Pseudoephedrine',
  'Pseudoephedrine / Guaifenesin',
  'Psorcon E',
  'Pulmicort Flexhaler',
  'Pulmozyme',
  'Purinethol',
  'Pylera',
  'Pyrazinamide',
  'Pyridium',
  'Pyridostigmine',
  'Pyrimethamine',
  'Quadramet',
  'Qualaquin',
  'Quazepam',
  'Questran',
  'Quetiapine Fumarate',
  'Quinapril Hydrochloride',
  'Quinidex',
  'Quinidine',
  'Quinidine Gluconate',
  'Quinidine Sulfate',
  'Quinupristin and Dalfopristin',
  'Quixin',
  'Qutenza',
  'Qvar',
  'R-Gene 10',
  'Rabavert',
  'Rabeprazole Sodium',
  'Rabies Immune Globulin',
  'Rabies Vaccine',
  'Radiogardase',
  'Raloxifene',
  'Raltegravir',
  'Ramelteon',
  'Ramipril',
  'Ranexa',
  'Ranibizumab',
  'Ranitidine Bismuth Citrate',
  'Ranitidine Hcl',
  'Ranitidine Hydrochloride',
  'Ranolazine',
  'Rapaflo',
  'Rapamune',
  'Raplon',
  'Raptiva',
  'Rasagiline',
  'Rasburicase',
  'Rattlesnake Antivenin',
  'Raxar',
  'Razadyne ER',
  'Rebetol',
  'Rebetron',
  'Rebif',
  'Reclast',
  'Recombinate',
  'Refacto',
  'Refludan',
  'Regadenoson',
  'Reglan',
  'Regranex',
  'Relafen',
  'Relenza',
  'Relistor',
  'Relpax',
  'Remeron',
  'Remicade',
  'Remifentanil',
  'Remodulin',
  'Renagel',
  'Renese',
  'Renova',
  'Renvela',
  'ReoPro',
  'Repaglinide',
  'Repronex',
  'Requip',
  'Rescriptor',
  'Rescula',
  'Restasis',
  'Restoril',
  'Retapamulin',
  'Retavase',
  'Reteplase',
  'Retin-A Micro',
  'Retisert',
  'Retrovir',
  'Revatio',
  'Revex',
  'Revia',
  'Revlimid',
  'Reyataz',
  'Rezulin',
  'Rheumatrex',
  'Rhinocort Aqua',
  'Rhogam',
  'Rhogam Ultra-Filtered Plus',
  'Rhophylac',
  'RiaSTAP',
  'Ribavirin',
  'Rifabutin',
  'Rifadin',
  'Rifamate',
  'Rifampin',
  'Rifampin and Isoniazid',
  'Rifapentine',
  'Rifater',
  'Rifaximin',
  'Rilonacept',
  'Rilutek',
  'Riluzole',
  'Rimantadine',
  'Rimexolone',
  'Rimso-50',
  "Ringer's Solution",
  'Riomet',
  'Risedronate Sodium',
  'Risperdal',
  'Risperdal Consta',
  'Risperidone',
  'Ritalin',
  'Ritonavir',
  'Rituxan',
  'Rituximab',
  'Rivastigmine Tartrate',
  'Rizatriptan Benzoate',
  'Robaxin',
  'Robaxisal',
  'Robinul',
  'Robitussin Ac',
  'Rocaltrol',
  'Rocephin',
  'Rocuronium Bromide',
  'Rofecoxib',
  'Roferon-A',
  'Romazicon',
  'Romidepsin',
  'Romiplostim',
  'Rondec',
  'Ropinirole',
  'Ropinirole Hcl',
  'Ropivacaine Hcl',
  'Rosanil',
  'Rosiglitazone Maleate',
  'Rosuvastatin Calcium',
  'Rotarix',
  'RotaTeq',
  'Rotavirus Vaccine, Live, Oral',
  'Rotigotine',
  'Rowasa',
  'Roxanol',
  'Roxicet',
  'Roxicodone',
  'Rozerem',
  'Rubella Vaccine',
  'Rufinamide',
  'Rythmol',
  'Rythmol SR',
  'Ryzolt',
  'Sabril',
  'Sacrosidase',
  'Saizen',
  'Salagen',
  'Salmeterol Xinafoate',
  'Salsalate',
  'Seconal Sodium',
  'SecreFlo',
  'Secretin',
  'Sectral',
  'Selegiline Hcl',
  'Selegiline Hydrochloride',
  'Selegiline Transdermal System',
  'Selenium',
  'Selsun',
  'Selzentry',
  'Semprex D',
  'Sensipar',
  'Sensorcaine',
  'Septocaine',
  'Septra',
  'Serax',
  'Serevent Diskus',
  'Sermorelin',
  'Sermorelin Acetate',
  'Seroquel',
  'Seroquel XR',
  'Serostim',
  'Serostim LQ',
  'Sertaconazole Nitrate',
  'Sertraline Hcl',
  'Serzone',
  'Sevelamer Carbonate',
  'Sevelamer Hcl',
  'Sevoflurane',
  'Sibutramine Hydrochloride Monohydrate',
  'Sildenafil Citrate',
  'Silenor',
  'Silodosin',
  'Silvadene',
  'Silver Sulfadiazine',
  'Simcor',
  'Simponi',
  'Simulect',
  'Simvastatin',
  'Sincalide',
  'Sinemet',
  'Sinemet CR',
  'Sinequan',
  'Singulair',
  'Sirolimus',
  'Sitagliptin Metformin HCL',
  'Sitagliptin Phosphate',
  'Skelaxin',
  'Skelid',
  'Slo-phyllin',
  'Slow-K',
  'Sodium Acetate',
  'Sodium Bicarbonate',
  'Sodium ferric gluconate',
  'Sodium Fluoride',
  'Sodium Hyaluronate',
  'Sodium Iodide I 131',
  'Sodium Lactate',
  'Sodium Oxybate',
  'Sodium Phenylbutyrate',
  'Sodium Phosphate Monobasic',
  'Sodium Polystyrene Sulfonate',
  'Sodium Sulfacetamide',
  'Solage',
  'Solaraze',
  'Solifenacin Succinate',
  'Soliris',
  'Solodyn',
  'Soltamox',
  'Solu Cortef',
  'Solu Medrol',
  'Soma',
  'Soma Compound',
  'Somatrem',
  'Somatropin',
  'Somavert',
  'Sonata',
  'Sorafenib',
  'Soriatane',
  'Sotalol',
  'Sotalol Hcl',
  'Sotradecol',
  'Sparfloxacin',
  'Spectazole',
  'Spectinomycin',
  'Spectracef',
  'Zyvox',
];
